### ISSUE TITLE
Hover states on arrow buttons

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#10]
Lovely little animation! 2 things for this though:

1. When hovering out of the animation before it is over, the normal state just appears, which makes it seem a little jagged. 
Could we somehow rewind the animation, so that it seems smooth in the same way that the underline animation in the nav bar does?

2. Could the arrow animation also be played when the user is hovering a CTA image? Would seem more natural. Image or arrow link, they all let you navigate to a new page, so the pattern should be the same, I think :)

**Comment by annaehrnsperger** [comment]
1. Was thinking about this, but couldn't come up with a good solution. We could play the animation 2, 3 times and at the end it goes back to its initial state?

**Comment by jacoblindblad** [comment]
1. I think one time is the most clean. It's more about what happens when the user moves out of the hit area before the animation has been completed. See gif: 
![hover](https://user-images.githubusercontent.com/53619202/102487117-544d5f80-406a-11eb-9c04-4a1861adc7de.gif)

**Comment by annaehrnsperger** [comment]
Now the animation plays once completely when hovering over it. I think that's fine! What do you think?

**Comment by jacoblindblad** [comment]
Yes, soooo nice! Thank you! <3
