### ISSUE TITLE
Site credits

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#11]
I like it! Would it be possible to give it 10% more love? :)

Perhaps "Jacob" and "Anna" could fall from different heights and x-pos, so it doesn't seem so bombastic? They fall at the same time like boom.

Also, would it perhaps look better if our names were inside of a white / red or blue box? It looks a little strange sometimes with the text on top of text.

Sometimes with these physics engines you can also drag the elements / throw them around. Is this an option for us?

**Comment by annaehrnsperger** [comment]
Sure! Just wanted to hear your opinion if this is something we can use. If you have other ideas what should happen, please let me know.

**Comment by jacoblindblad** [comment]
I think we should use it, because it looks very nice. Just needs a little refinement, I think :)

**Comment by jacoblindblad** [comment]
Hey! I completely understand & appreciate that you want to be done with the site soon, but I was looking at the site credit again today, and don't think that that's it's quite there yet. To me it's a little weird now, because the 2 boxes just land very flat on the bottom of the footer and then that's it. What are your thoughts?

Could we do something that doesn't take too much time, but still spiffs it all up a bit?
- How about for example using the the dark overlay to emphasise the white boxes?
- Could the physics be more playful? An idea: one flies with medium/high speed from the left towards the right and the other is dropped with lower speed but in a curve (or something)?
- Would it be possible to grab the boxes and toss them around?

I'm just thinking that this kind of easter egg should either be a pleasant surprise or not be there at all :)
Please don't take this as a critique of the work you've done on the site credits so far. 
Would love to hear your thoughts on this :)
