### ISSUE TITLE
Journal CTA

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#13]
Could we force the images to be 1:1 / Square format and always have the CTA copy align to the bottom of the image? It will make the different components of the module look more connected than now, I think :) 

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/53619202/102111226-6646bc80-3e36-11eb-8e79-9db6b808080c.png">

**Comment by annaehrnsperger** [comment]
Still have to spend some time with safari obviously, in Firefox it looks fine ...
