### ISSUE TITLE
Donate page

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#15]
Is there any way to animate the copy in & out when changing options? I'm thinking both "Give once" vs "Give Monthly" and the copy that explains what each amount results in.

**Comment by annaehrnsperger** [comment]
Was playing a bit around with this one ... It's actually tricky to animate the color. Also the copy, it's basically just text that exchanges itself within a <p>. There are currently no separate dom elements, that could be animated. If it's not super important to you, I would skip this issue.

**Comment by jacoblindblad** [comment]
Of course, that's fine! Thanks.
