### ISSUE TITLE
Animation for Journal tags (and filtering using Journal tags)

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#19]
Would it be possible to:

1. Animate the hover state on the Journal tags _in_ so that they don't appear out of nowhere on for instance the front page
2. Move the tags closer to the "Tagged with" label, so that the gap isn't as big?
3. Have the inactive state of the tags sit closer to each other (10px), and then let that space grow when the rounded corner button appears? :)
4. When filtering Journal posts on /Journal could the animation _in_ and _out_ be a little softer?

**Comment by annaehrnsperger** [comment]
Fixed
