### ISSUE TITLE
General loading stuff

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#22]
**Images**
When visiting the website on an empty cache, most images are first shown for a split second as super low res, and then the real image is loaded in. Is there a way to lazy load these, so that the user only sees the super low res on a very slow connection of if they are very fast at scrolling right when they enter the site?

**Click and animation**
The response time from clicking something to the in-out animation is very smooth on desktop, but it seems a little hesitant / unresponsive on mobile (tested on an iPhone XS). Is there something we can do here?

**Comment by annaehrnsperger** [comment]
Images
For image compression and lazy loading I'm using https://www.gatsbyjs.com/plugins/gatsby-image/ which works great. So yes, on a slow connection the blurred image is shown for a long time. Overall I let it do its magic and usually don't make any adjustments.

Click and animation
Should be much smoother now.
