### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#4]
Video player:

- Has the "Awareness" video (under "The Solution") letterbox / black bars added, or is that the container? If it is the container, could we change it, so that it always reflects the video's aspect ratio x fixed width?
- When the video is playing, the controls can fade out, as soon as the user MouseOuts
- Add Pause icon (sent on Slack)
- Would it be possible to toggle play/pause anywhere on the video, not only in the corner?

**Comment by annaehrnsperger** [comment]
The black bars belong to the video. The height adjusts automatically!
