### ISSUE TITLE
Cookies?

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#5]
Are we using cookies?
If yes:

- can we provide some information to the legal assistant who will be writing Kweras cookies policy text?
- do we need a consent bar? (tbd from legal assistant, apparently there are new rules?)

**Comment by annaehrnsperger** [comment]
Currently the site doesn't use cookies. 
Stripe probably does, but I will have to take a closer look when it's implemented!

**Comment by jacoblindblad** [comment]
Now that we will be using GA, we should probably create a cookies consent bar. Am awaiting final go from the attorney from law firm Plesner, she said there were some new rules regarding the cookie bars.
