### ISSUE TITLE
Team module ("List")

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#9]
1. The copy on the "List" module is a little too wide compared to the design. The image should preferably be 7col and the copy 6 col 
2. Would it be possible to have the "not yet active" team member card at the right side of the page be faded out (30% opacity / white overlay in 70%) and animate it to 100% when it moves in through scrolling, like in the design?

**Comment by annaehrnsperger** [comment]
2. Haven't forgotten! Just isn't implemented yet. :-)

**Comment by annaehrnsperger** [comment]
I had to add a bit of left padding in order to improve the scroll experience – hope this is fine with you.
